"""chore: remove unnecessary db relationship

Revision ID: 94fa5c416d55
Revises: ef7ab09343b3
Create Date: 2022-05-20 11:31:13.826515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fa5c416d55'
down_revision = 'ef7ab09343b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_genre')
    op.drop_table('artist_genre')
    op.add_column('artists', sa.Column('genres', sa.String(length=50), nullable=False))
    op.add_column('venues', sa.Column('genres', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    op.create_table('artist_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name='artist_genre_artist_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='artist_genre_pkey')
    )
    op.create_table('venue_genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name='venue_genre_venue_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='venue_genre_pkey')
    )
    # ### end Alembic commands ###
